### ISSUE TITLE
FAIL: test_tm_job_split_angles (test_tmjob.TestTMJob.test_tm_job_split_angles)

### ISSUE THREAD

**Issue by junhe123** [SBC-Utrecht/pytom-template-matching-gpu#59] opened 2023-11-06 15:19 UTC
Hi everyone,

I am trying to install and test pytom-template matching on my own workstation, with unbuntu 18.04, nvidia 2080ti and cuda 11.2.

No error message during the installation. However, I got the following error message (see the attached snapshot) for the unittests. Anyone know how to fix the issue?

Thanks in advance!
Jun He
![Screenshot from 2023-11-06 23-12-07](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/assets/42323103/8ded1091-fc39-4bbc-b901-ebc1774e5528)

**Comment by sroet** [comment] 2023-11-06 15:43
This is a duplicate of #58 (after that author updated to the most recent version), 
Quoting [this answer](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/issues/58#issuecomment-1793525597):
> Hmm, not super clear to me what is going wrong in this test. I suspect it's not a critical issue, but rather a small nunerical inconsistency. Definitely needs to be solved. Thanks for reporting it and will get back to you about a solution.
> 
> As all other tests pass, the software is fuctioning correctly. So, you can safely use it.

I will close this issue as a duplicate, please subscribe to notifications of #58 if you are interested on receiving updates on this issue

**Closed by sroet** 2023-11-06 15:43 UTC
